apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimiter-deployment
  labels:
    app: ratelimiter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ratelimiter
  template:
    metadata:
      labels:
        app: ratelimiter
    spec:
      containers:
        - name: ratelimiter
          image: ghcr.io/ranser102/ratelimiter-fixed-window-counter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
