apiVersion: v1
kind: Service
metadata:
  name: ratelimiter-service
spec:
  selector:
    app: ratelimiter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
  
