# Use the official Python base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY src/main.py src/ratelimit_memcached.py src/requirements.txt /app/

# Install any needed packages specified in requirements.txt
# Uncomment the following line if you have a requirements.txt file
RUN pip install --no-cache-dir -r /app/requirements.txt

# Create a non-root user and group
RUN groupadd -r appuser && useradd -r -g appuser appuser

# Change ownership of the /app directory to the non-root user
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser

# Print the content of the local directory
RUN ls -la /app

# Run main.py when the container launches
CMD ["python", "main.py"]
